### PR TITLE
Feature: Filters

### PR DESCRIPTION
**Pull request by cyborch**
Adds really simple filtering implementation.

This reuses the existing `sensitive` feature to blur statuses which match filters with `warn` action, and hides statuses which match filters with hide action.

### CODE REVIEW

**Comment by cheeaun** [comment]
Thanks! Few quick notes:

- This won't work for multiple accounts. I'm still figuring out what's the best way to do this, like maybe namespaced keys in localStorage, which means I need to standardise something on my side first.
- For Home timeline, there's a websocket connection that listens to `status.update` event which **updates** the status (if edited). I could think of a super-rare weird use-case when a status contains a filter word, gets filtered out, but later edited by the author to **not** contain it, so it shouldn't be filtered anymore 😂😂

Side notes:

- I'm still figuring out the reasons why and how people use filters. And how it'll affect usage in the long term.
- I personally think that there could be a better way to do this (this'll take time).

**Comment by cyborch** [comment]
Thank you for the comments.

This forced me to use a better solution.

Instead, I am using the `filtered` property on a status. This works across multiple accounts since it acts on the individual status instead of depending on a pre-fetched list of filters.

It also resolves the issue with `status.update` streamed events.

**Comment by cheeaun** [comment]
It seems that some commits are missing, I only see 1 file changed here.

---

Anyway, to set expectations, I won't be merging this or implement this yet, until I get the full picture. This will stay as a "wait-and-see" feature request.

Few reasons:

1. I had a rough look at the documentation, turns out it's quite complicated. One of the things that I think would be troublesome is the filters' `expires_in` key.
2. I looked at how it's implemented in Mastodon's and Pinafore's source code and noticed a few more edge cases.
3. I'm quite keen in keeping the app minimalistic, so adding features require a lot of careful planning because it'll end up a lot of maintenance work for me.
4. I personally don't think (manual) filtering is the right solution. I know that there are folks who wants complete control over their timeline (custom algo, custom filtering, regex?, hashtag following) but these features are _way_ too technical. For non-tech folks, this is too much manual work and complicated.
5. In cases of harassment, I do think mute/block/report features would be higher priority than this - possibly smaller scope too (probably via a menu in Detail view and Account sheet)

**Comment by cheeaun** [comment]
Currently a partial implementation on [production](https://phanpy.social).

**Pull request closed without merging**
